<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup><OutputType>Exe</OutputType><TargetFramework>net8.0-windows</TargetFramework><UseWPF>true</UseWPF><ImplicitUsings>enable</ImplicitUsings></PropertyGroup>
  <ItemGroup>
    <ProjectReference Include="../../WordleItaliano/WordleItaliano.csproj" AdditionalProperties="WordleTestBuild=true" />
    <Resource Include="../../WordleItaliano/Assets/*.png" Link="Assets/%(Filename)%(Extension)" />
    <Content Include="../../WordleItaliano/Data/*.json" Link="Data/%(Filename)%(Extension)" CopyToOutputDirectory="PreserveNewest" />
    <Content Include="../../WordleItaliano/appsettings.json" Link="appsettings.json" CopyToOutputDirectory="PreserveNewest" />
  </ItemGroup>
</Project>
